FROM node:lts AS builder

WORKDIR /app/webui
RUN corepack enable
COPY webui ./
RUN yarn build-embed

FROM nginx:stable

RUN adduser --disabled-password --uid 1000 appuser
RUN mkdir -p /tmp/client_temp /tmp/proxy_temp /tmp/fastcgi_temp /tmp/uwsgi_temp /tmp/scgi_temp && chown -R 1000:1000 /tmp

COPY --from=builder /app/webui/dist /usr/share/nginx/html
COPY ./webui/nginx.conf /etc/nginx/nginx.conf
