FROM golang:1.17 AS builder

WORKDIR /app
COPY . .

RUN go build -o webapi ./cmd/webapi

FROM debian:bullseye-slim

WORKDIR /app

COPY --from=builder /app/webapi /app/webapi
COPY --from=builder /app/conf /app/conf
COPY --from=builder /app/service/database/migrations /app/service/database/migrations

RUN mkdir -p /app/tmp/uploads/attachments /app/tmp/uploads/group-photos /app/tmp/uploads/profile-pictures
RUN chown -R 1000:1000 /app/tmp

USER 1000

EXPOSE 3000

CMD ["/app/webapi"]
