FROM golang:1.17 AS builder

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y gcc

RUN go build -tags webui -o webapi ./cmd/webapi

FROM debian:bullseye-slim

RUN useradd -u 1000 appuser

WORKDIR /app

COPY --from=builder /app/webapi /app/webapi
COPY --from=builder /app/conf /app/conf
COPY --from=builder /app/tmp /app/tmp
COPY --from=builder /app/service/database/migrations /app/service/database/migrations

USER 1000

EXPOSE 3000

CMD ["/app/webapi"]
